source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "Flicks" do
    pod 'AFNetworking', '~> 3.0'
    pod "youtube-ios-player-helper", "~> 0.1.1"
    pod 'MBProgressHUD'
end
